# Numpy Advanced

### Exploring Numpy's Ufuncs - Universal Functions! These are generally much faster than creating your own functions

## Numpy UFuncs: Add, Sum, Plus Operators

In [6]:
import numpy as np

### Dimensions of Arrays using newaxis and squeeze

In [82]:
## Lets say we have an array of numbers 0-9
A =  np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
## Lets say we have an array of numbers 0-9 but their in a random order and can repeat
B = np.random.randint(0,10,(1,10))
B

array([[3, 1, 3, 3, 2, 7, 9, 8, 7, 6]])

In [14]:
A.shape

(10,)

In [16]:
## Notice how B is a 1x10 but A is not
B.shape

(1, 10)

In [20]:
## We can fix this using numpy's newaxis
C = A[np.newaxis,:]
C.shape

(1, 10)

### Lets use the plus and add operators

In [30]:
## Now lets try to add the arrays
## We are able to do this because the arrays are the same shape, which is why we did the above

D = B+C
D

array([[ 3,  2,  5,  6,  6, 12, 15, 15, 15, 15]])

In [34]:
D.shape

(1, 10)

In [36]:
## We can also reduce the dimension of an array
## Notice it is now the same shape as A

D = np.squeeze(D)
D.shape

(10,)

In [41]:
D

array([ 3,  2,  5,  6,  6, 12, 15, 15, 15, 15])

In [43]:
A.shape

(10,)

In [86]:
## Now that A and D are the same dimensions we can add them
## Lets use the add operator!

E = np.add(A,D)
E

array([ 3,  3,  7,  9, 10, 17, 21, 22, 23, 24])

### sum() of arrays

In [49]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
## This is the sum of all ints in A
np.sum(A)

45

In [57]:
## The sum is very helpful with large arrays like his one!

A = np.arange(100).reshape(2,2,5,5)

In [67]:
A

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

In [59]:
## A is a 4 dimensional array
A.ndim

4

In [61]:
np.sum(A)

4950

In [69]:
## Notice if we use the sum function in this mannor we reduce the dimensions of the matrix
B = A.sum(axis=0)
B.shape

(2, 5, 5)

In [73]:
B

array([[[ 50,  52,  54,  56,  58],
        [ 60,  62,  64,  66,  68],
        [ 70,  72,  74,  76,  78],
        [ 80,  82,  84,  86,  88],
        [ 90,  92,  94,  96,  98]],

       [[100, 102, 104, 106, 108],
        [110, 112, 114, 116, 118],
        [120, 122, 124, 126, 128],
        [130, 132, 134, 136, 138],
        [140, 142, 144, 146, 148]]])

In [71]:
## We can do this again for a smaller matrix, further summing the elements in the matrix
C = B.sum(axis=0)
C.shape

(5, 5)

In [75]:
C

array([[150, 154, 158, 162, 166],
       [170, 174, 178, 182, 186],
       [190, 194, 198, 202, 206],
       [210, 214, 218, 222, 226],
       [230, 234, 238, 242, 246]])

In [77]:
## Now lets do this once more!

C.sum(axis=0)

array([ 950,  970,  990, 1010, 1030])